export const industries = [
  "Software", "Agriculture", "Manufacturing", "Healthcare", "Finance", "Education", "Engineering", "Design"
];

export const mentors = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Senior Engineer",
    company: "Google",
    industry: "Software",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    bio: "10+ years in full-stack development. Passionate about mentoring the next generation of engineers.",
    skills: ["React", "Node.js", "Python", "System Design", "AWS"],
    followers: 1240,
    communities: 2,
    posts: 45,
    experience: 12,
    guidance: "Career guidance, code reviews, interview prep, and technical mentorship.",
    coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=300&fit=crop",
  },
  {
    id: "2",
    name: "James Okafor",
    role: "Farm Operations Director",
    company: "GreenFields Co.",
    industry: "Agriculture",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    bio: "Leading sustainable farming initiatives across East Africa. Building the future of agriculture.",
    skills: ["Agribusiness", "Crop Science", "Supply Chain", "Sustainability"],
    followers: 830,
    communities: 1,
    posts: 32,
    experience: 15,
    guidance: "Agricultural entrepreneurship, sustainable farming, and agritech adoption.",
    coverImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&h=300&fit=crop",
  },
  {
    id: "3",
    name: "Dr. Amina Patel",
    role: "Chief Medical Officer",
    company: "MediCare Plus",
    industry: "Healthcare",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face",
    bio: "Dedicated to improving healthcare access and mentoring medical students.",
    skills: ["Clinical Research", "Healthcare Management", "Public Health", "Telemedicine"],
    followers: 2100,
    communities: 3,
    posts: 67,
    experience: 20,
    guidance: "Medical career paths, research mentorship, and healthcare innovation.",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=300&fit=crop",
  },
  {
    id: "4",
    name: "Michael Torres",
    role: "VP of Finance",
    company: "CapitalBridge",
    industry: "Finance",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    bio: "Helping students navigate the world of finance and investment banking.",
    skills: ["Financial Analysis", "Investment Banking", "Risk Management", "Fintech"],
    followers: 960,
    communities: 1,
    posts: 28,
    experience: 14,
    guidance: "Finance career advice, CFA prep, and fintech opportunities.",
    coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=300&fit=crop",
  },
  {
    id: "5",
    name: "Lisa Wang",
    role: "Product Design Lead",
    company: "Figma",
    industry: "Design",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    bio: "Crafting user experiences that delight. Mentor for aspiring designers.",
    skills: ["UI/UX Design", "Figma", "Design Systems", "User Research", "Prototyping"],
    followers: 1800,
    communities: 2,
    posts: 52,
    experience: 9,
    guidance: "Portfolio reviews, design thinking, and breaking into tech design.",
    coverImage: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=300&fit=crop",
  },
  {
    id: "6",
    name: "David Kim",
    role: "ML Engineer",
    company: "OpenAI",
    industry: "Software",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    bio: "Building AI systems. Love teaching machine learning concepts.",
    skills: ["Machine Learning", "Python", "TensorFlow", "NLP", "Data Science"],
    followers: 3200,
    communities: 2,
    posts: 89,
    experience: 8,
    guidance: "AI/ML career paths, research papers, and project mentorship.",
    coverImage: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=300&fit=crop",
  },
];

export const communities = [
  { id: "1", name: "Software Engineers Hub", mentorId: "1", mentorName: "Sarah Chen", mentorAvatar: mentors[0].avatar, members: 450, unread: 3, industry: "Software" },
  { id: "2", name: "AgriTech Innovators", mentorId: "2", mentorName: "James Okafor", mentorAvatar: mentors[1].avatar, members: 210, unread: 0, industry: "Agriculture" },
  { id: "3", name: "Healthcare Leaders", mentorId: "3", mentorName: "Dr. Amina Patel", mentorAvatar: mentors[2].avatar, members: 680, unread: 5, industry: "Healthcare" },
  { id: "4", name: "AI & ML Community", mentorId: "6", mentorName: "David Kim", mentorAvatar: mentors[5].avatar, members: 1200, unread: 12, industry: "Software" },
  { id: "5", name: "Design Circle", mentorId: "5", mentorName: "Lisa Wang", mentorAvatar: mentors[4].avatar, members: 520, unread: 1, industry: "Design" },
];

export const opportunities = [
  { id: "1", title: "Frontend Intern", type: "Internship", company: "Google", location: "Remote", deadline: "2026-04-15", mentorName: "Sarah Chen", mentorId: "1", industry: "Software", description: "Join our frontend team for a 3-month internship working on Google Workspace products.", requirements: ["React/Angular experience", "HTML/CSS proficiency", "Currently enrolled in CS program"] },
  { id: "2", title: "Junior Data Scientist", type: "Job", company: "OpenAI", location: "San Francisco, CA", deadline: "2026-04-30", mentorName: "David Kim", mentorId: "6", industry: "Software", description: "Full-time role working on large language models and data pipelines.", requirements: ["MS in CS or related field", "Python proficiency", "ML framework experience"] },
  { id: "3", title: "Agricultural Research Assistant", type: "Internship", company: "GreenFields Co.", location: "Nairobi, Kenya", deadline: "2026-05-01", mentorName: "James Okafor", mentorId: "2", industry: "Agriculture", description: "Assist in sustainable farming research and field trials.", requirements: ["Agriculture or Biology major", "Field work experience preferred"] },
  { id: "4", title: "UX Design Workshop", type: "Workshop", company: "Figma", location: "Online", deadline: "2026-04-10", mentorName: "Lisa Wang", mentorId: "5", industry: "Design", description: "Hands-on workshop covering design systems and component libraries.", requirements: ["Basic Figma knowledge", "Portfolio with 2+ projects"] },
  { id: "5", title: "Clinical Research Intern", type: "Internship", company: "MediCare Plus", location: "Boston, MA", deadline: "2026-05-15", mentorName: "Dr. Amina Patel", mentorId: "3", industry: "Healthcare", description: "Support clinical trials and patient data analysis.", requirements: ["Pre-med or Public Health student", "Strong attention to detail"] },
];

export const posts = [
  { id: "1", authorName: "Sarah Chen", authorAvatar: mentors[0].avatar, isMentor: true, timestamp: "2h ago", content: "Just posted a new internship opportunity for frontend developers! Check out the Opportunities tab. 🚀", likes: 24, comments: 8 },
  { id: "2", authorName: "Alex Johnson", authorAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=150&h=150&fit=crop&crop=face", isMentor: false, timestamp: "4h ago", content: "Can anyone recommend resources for learning system design? I have an interview coming up.", likes: 15, comments: 12 },
  { id: "3", authorName: "David Kim", authorAvatar: mentors[5].avatar, isMentor: true, timestamp: "1d ago", content: "Great question about system design! I'd recommend starting with 'Designing Data-Intensive Applications' by Martin Kleppmann. Also check out the System Design Primer on GitHub.", likes: 42, comments: 6 },
  { id: "4", authorName: "Priya Sharma", authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face", isMentor: false, timestamp: "1d ago", content: "Just got accepted into the Google internship! Thank you Sarah for the mentorship and guidance! 🎉", likes: 89, comments: 23 },
];
